Repository open-services-group/metrics, pull requests merged in 2022-03, with the labels that each got.

#20 Add repo analysis notebook
  notebooks/Repo_Analysis.ipynb
  notebooks/s3_communication.py
Labels: lgtm, size/XXL, approved

#25 Add contributors table
  .pre-commit-config.yaml
  Pipfile
  Pipfile.lock
  notebooks/Repo_Analysis.ipynb
  notebooks/repo-metrics.ipynb
Labels: size/XXL, approved

#26 Add metric request issue template
  .github/ISSUE_TEMPLATE/metric_request.md
Labels: size/S, approved
